#*
#* Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#* SPDX-License-Identifier: MIT-0
#*
#* Permission is hereby granted, free of charge, to any person obtaining a copy of this
#* software and associated documentation files (the "Software"), to deal in the Software
#* without restriction, including without limitation the rights to use, copy, modify,
#* merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
#* permit persons to whom the Software is furnished to do so.
#*
#* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
#* INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
#* PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
#* HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
#* OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
#* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#*

#------------------------------------------------------------------------------
#
# Template: dhmc-cfn-template.yaml
# Purpose:  CloudFormation template to deploy a Quick Setup configuration for Default Host Management Configuration.
#
#------------------------------------------------------------------------------

AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to deploy a Quick Setup configuration for Default Host Management Configuration.
Resources:
  DHMCQuickSetupConfigurationManager:
    Type: AWS::SSMQuickSetup::ConfigurationManager
    Properties:
      Name: qs-dhmc
      Description: Enable Default Host Management configuration for the AWS Organization
      ConfigurationDefinitions:
      - Type: AWSQuickSetupType-DHMC
        Parameters:
          UpdateSSMAgent: 'true'
          TargetOrganizationalUnits: r-1abc
          TargetRegions: eu-north-1, ap-south-1, eu-west-3, us-east-2, eu-west-1, eu-central-1,
            sa-east-1, us-east-1, ap-northeast-2, eu-west-2, ap-northeast-1, us-west-2,
            us-west-1, ap-southeast-1, ap-southeast-2, ca-central-1